### ISSUE TITLE
Broken README links to folders

### ISSUE THREAD

**Issue by Rubenmp** [fjsaezm/mcd-opt#1]

**Comment by fjsaezm** [comment]
Fixed!

**Comment by Rubenmp** [comment]
Minor comment: relative links are more robust since they do not depend on anything else. 
`[this subtext](subpro/subtext.md)`
You could change your nickname, even git host provider, and the relative link would still be valid, not the absolute one.
For small projects, it is not a big deal, but for big projects without automatic link checks... relative is desirable IMHO.
